version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.16
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: 'Install Git LFS'
          command: |
            curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
            sudo apt-get install git-lfs
      - run:
          name: 'Pull submodules'
          command: |
            git submodule init
            git submodule update --remote
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: install-packages
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: build-project
          command: 'yarn run build'
      - run:
          name: generate-static-pages
          command: 'yarn run export'
      - persist_to_workspace:
          root: ./
          paths:
            - dist
  deploy:
    working_directory: ~/repo
    docker:
      - image: cimg/python
    steps:
      - attach_workspace:
          at: ./
      - aws-s3/sync:
          from: dist
          to: 's3://ag7if-blog.the-hawk.us/'
          overwrite: true

workflows:
  version: 2.1
  build-deploy:
    jobs:
      - build
      - deploy:
          context: aws-thus
          requires:
            - build
          filters:
            branches:
              only: master
